### ISSUE TITLE
Make REPL text / history READ ONLY

### ISSUE THREAD

**Issue by ntoll** [ntoll/mu#20]
It's possible to move the cursor using the mouse to another location in the text (old output) and start typing. We shouldn't be able to do this! ;-)

**Comment by alistair-broomhead** [comment]
To me it seems that this is best done by splitting the display of the REPL into two elements, a TextView or QScintilla for history, and a TextEdit or QScintilla for current input. The model would then contain a list of commands, and validation to check whether a new command was complete (two newlines). This then neatly solves the problem of being able to scroll through part commands.

**Comment by ntoll** [comment]
Fixed by e85aea75e1f9ce7302528634d054280c7d594945
