### ISSUE TITLE
Saved script should add extension if not given

### ISSUE THREAD

**Issue by carlosperate** [ntoll/mu#34]
Clicking the save button prompts the user to select a location and filename for the Python script. If not extension is included in the filename, mu should automatically attach it.

**Comment by NDevox** [comment]
Built a fix for this (went with #47).

Will push tomorrow. Need to branch a few things....

**Comment by NDevox** [comment]
Pull #54 does this for me on win10 and on ubuntu.

**Comment by NDevox** [comment]
Made updates to #54. Current state of affairs would force files to be a .py (by always adding it if the filename does not end with .py)
