### ISSUE TITLE
Ensure REPL works cross platform.

### ISSUE THREAD

**Issue by ntoll** [ntoll/mu#41]
Currently the REPL only works in Linux. This needs to change so that it works in:

- [x] Windows 7/8/10
- [x] OS X
- [x] Raspberry Pi

Given the cross platform nature of Qt this (hopefully) shouldn't be an onerous task. The major sticking point will be upon device detection.

Unfortunately, Windows does not come with serial/COM drivers for the micro:bit installed by default (happily, Linux and OSX do).

If you're on Windows, in order to make this work you should use the mbedWinSerial_16466.exe file (found here: https://developer.mbed.org/media/downloads/drivers/mbedWinSerial_16466.exe) to install the correct drivers. You MUST have your micro:bit plugged into your computer when you run this command.

For more information and the latest versions of this driver please visit:

https://developer.mbed.org/handbook/Windows-serial-configuration

**Comment by inglesp** [comment]
Why do we think it doesn't work on OS X?  It's worked for me!

**Comment by ntoll** [comment]
@inglesp it just needed someone to check it! ;-) Thanks.

**Comment by ntoll** [comment]
Closing because all three target platforms have been tested and shown to work.
