### ISSUE TITLE
REPL doesn't work with automatically built binary on Linux.

### ISSUE THREAD

**Issue by ntoll** [ntoll/mu#75]
What it says. When run from source locally, it works fine.

I'm using vanilla Debian Jessie with the expected QT libraries installed.

**Comment by ntoll** [comment]
@carlosperate any idea what might be going on..?

**Comment by carlosperate** [comment]
Haven't tested the REPL under Linux directly, most tests I've done were
through a virtual machine. I'll check it out later tonight once I get a
chance.

**Comment by carlosperate** [comment]
It looks like mu needs sudo access for the REPL, in my test system (virtual machine running the minimal version of Ubuntu 15.04 64bit with xfce) I needed it for both the pre-built version and running locally. Can you run locally without sudo?

**Comment by ntoll** [comment]
Working from source works fine without sudo if you're in the right group for USB/serial communications. I tried running it *as* sudo and it still didn't work (I checked with running from source immediately after and it *did* work). This suggests something amiss with the binary.

**Comment by carlosperate** [comment]
I'll see if I can install a Jessie on a vm and replicate tomorrow. Since the issue might be specific to the CI server build environment, I'll create a temp branch to create builds that print the specific exception on console.

**Comment by kushaldas** [comment]
For me in Fedora it did not work even from the source.

**Comment by kushaldas** [comment]
On my Fedora 23 box:

>>> ports = QSerialPortInfo.availablePorts()
>>> for p in ports:
...   print p.manufacturer(), p.serialNumber(), p.description()
... 
MBED 9900023431864e450003100e0000003b00000000cc4d28bd MBED CMSIS-DAP

**Comment by kushaldas** [comment]
The product and vendor identifier is coming as 

39985 and 32902 in Fedora 23.

**Comment by carlosperate** [comment]
I was finally able to replicate the issue on a debian virtual machine. Looks like the problem was due to the baud rate set before the port was opened, a bit more info on the PR submitted: https://github.com/ntoll/mu/pull/80
