### ISSUE TITLE
Add the ability to create a new Python script

### ISSUE THREAD

**Issue by ntoll** [ntoll/mu#9]
As a user, when I click the "New" button I expect to be asked for a name for my new script.

If such a script already exists I should be challenged about this and asked to select to back out or overwrite the existing script.

Upon completion I'm presented with an empty editor ready for me to code in. When I click "Save" the newly created script's name is correctly used.

**Comment by carlosperate** [comment]
What is the result when a file editor is already open? Will tabbed files be used?

**Comment by ntoll** [comment]
Fixed by #24
